bookstore/urls.py
from django.conf.urls import url
from django.contrib import admin
from .core import views as v

urlpatterns = [
    url(r'^$', v.home, name='home'),
    url(r'^teste/$', v.SomeProtectedView.as_view(), name='teste'),
    url(r'^adduser/$', v.adduser, name='adduser'),
    url(r'^customers/$', v.customer_list, name='customer_list'),
    # url(r'^customers/$', v.SomeProtectedView.as_view(), name='customer_list'),
    url(r'^books/$', v.BookList.as_view(), name='book_list'),
    url(r'^stores/$', v.StoreList.as_view(), name='store_list'),
    url(r'^stores/(?P<pk>\d+)/$', v.StoreDetail.as_view(), name='store_detail'),
    url(r'^admin/', admin.site.urls),
]

bookstore/core/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy
from .lists import gender_list, treatment_list, status_list


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        _('criado em'), auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(
        _('modificado em'), auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Person(models.Model):
    gender = models.CharField(_(u'gênero'), max_length=1, choices=gender_list)
    treatment = models.CharField(
        _('tratamento'), max_length=4, choices=treatment_list, blank=True)
    first_name = models.CharField(_('nome'), max_length=30)
    last_name = models.CharField(_('sobrenome'), max_length=30)
    birthday = models.DateTimeField(_('nascimento'), null=True, blank=True)
    email = models.EmailField(_('e-mail'), blank=True)
    active = models.BooleanField(_('ativo'), default=True)
    blocked = models.BooleanField(_('bloqueado'), default=False)

    class Meta:
        abstract = True

    def __str__(self):
        return self.first_name + " " + self.last_name

    full_name = property(__str__)


class Customer(Person):
    pass

    class Meta:
        ordering = ['first_name']
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'


class Seller(Person):
    internal = models.BooleanField(_('interno'), default=True)
    commissioned = models.BooleanField(_('comissionado'), default=True)
    commission = models.DecimalField(
        _(u'comissão'), max_digits=6, decimal_places=2, default=0.01, blank=True)

    class Meta:
        ordering = ['first_name']
        verbose_name = u'vendedor'
        verbose_name_plural = u'vendedores'


# Multi-Table Inheritance
class PF(Customer):
    cpf = models.CharField(_('CPF'), max_length=11)
    rg = models.CharField(_('RG'), max_length=10)

    class Meta:
        verbose_name = u'pessoa física'
        verbose_name_plural = u'pessoas físicas'


class PJ(Customer):
    cnpj = models.CharField(_('CNPJ'), max_length=14)
    ie = models.CharField(_('IE'), max_length=10)

    class Meta:
        verbose_name = u'pessoa jurídica'
        verbose_name_plural = u'pessoas jurídicas'


class Ordered(TimeStampedModel):
    customer = models.ForeignKey(
        'Customer', verbose_name=_('cliente'), related_name='cliente_pedido')
    status = models.CharField(
        _('status'), max_length=2, choices=status_list, default='pe')

    class Meta:
        ordering = ['-id']
        verbose_name = 'pedido'
        verbose_name_plural = 'pedidos'

    def __str__(self):
        return str(self.customer)


class Sale(models.Model):
    ordered = models.OneToOneField('Ordered', verbose_name=_('pedido'))
    paid = models.BooleanField(_('pago'), default=False)
    date_paid = models.DateTimeField(_('pago em'), null=True, blank=True)
    method = models.CharField(_('forma de pagto'), max_length=20, blank=True)
    deadline = models.CharField(
        _('prazo de entrega'), max_length=50, blank=True)

    class Meta:
        ordering = ['-id']
        verbose_name = 'venda'
        verbose_name_plural = 'vendas'

    def __str__(self):
        return str(self.ordered)


class Author(models.Model):
    name = models.CharField(_('nome'), max_length=50, unique=True)
    age = models.PositiveIntegerField(_('idade'))

    class Meta:
        ordering = ['name']
        verbose_name = 'autor'
        verbose_name_plural = 'autores'

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(_('nome'), max_length=50, unique=True)
    num_awards = models.PositiveIntegerField(_(u'prêmios'))

    class Meta:
        ordering = ['name']
        verbose_name = 'editora'
        verbose_name_plural = 'editoras'

    def __str__(self):
        return self.name


class Book(TimeStampedModel):
    isbn = models.IntegerField()
    name = models.CharField(_('nome'), max_length=50)
    rating = models.FloatField(_(u'classificação'))
    authors = models.ManyToManyField('Author', verbose_name='autores')
    publisher = models.ForeignKey('Publisher', verbose_name='editora')
    price = models.DecimalField(_(u'preço'), max_digits=5, decimal_places=2)
    stock_min = models.PositiveIntegerField(_(u'Estoque mínimo'), default=0)
    stock = models.IntegerField(_('Estoque atual'))

    class Meta:
        ordering = ['name']
        verbose_name = 'livro'
        verbose_name_plural = 'livros'

    def __str__(self):
        return self.name


class Store(models.Model):
    name = models.CharField(_('nome'), max_length=50)
    books = models.ManyToManyField('Book', verbose_name='livros')

    class Meta:
        ordering = ['name']
        verbose_name = 'loja'
        verbose_name_plural = 'lojas'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('store_detail', kwargs={'pk': self.pk})

bookstore/core/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

bookstore/core/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.conf import settings
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.models import User
from .forms import UserForm

from braces.views import GroupRequiredMixin
from .models import Customer, Book, Store


def home(request):
    return render(request, 'index.html')


def logged(request):
    return HttpResponse('Você está logado como {{ user.first_name }}')


def message(request):
    return HttpResponse('Acesso negado')


def customer_list(request):
    customers_all = Customer.objects.all()
    count = customers_all.count()

    paginator = Paginator(customers_all, 8)  # mostra 8 itens por pagina
    page = request.GET.get('page')
    try:
        customers = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        customers = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        customers = paginator.page(paginator.num_pages)
    ctx = {'customers': customers, 'count': count, 'name_plural': 'clientes'}
    return render(request, 'core/customer_list.html', ctx)


class CounterMixin(object):

    def get_context_data(self, **kwargs):
        ''' counter registers '''
        context = super(CounterMixin, self).get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        return context


class BookList(CounterMixin, ListView):
    template_name = 'core/book_list.html'
    model = Book
    context_object_name = 'books'
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super(BookList, self).get_context_data(**kwargs)
        context['name_plural'] = 'livros'
        return context

    def get_queryset(self):
        ''' use prefetch_related for m2m performance '''
        b = Book.objects.prefetch_related('authors').all()
        return b


class StoreList(CounterMixin, ListView):
    template_name = 'core/store_list.html'
    model = Store
    context_object_name = 'stores'

    def get_context_data(self, **kwargs):
        context = super(StoreList, self).get_context_data(**kwargs)
        context['name_plural'] = 'lojas'
        return context

    def get_queryset(self):
        ''' use prefetch_related for m2m performance '''
        s = Store.objects.prefetch_related('books').all()
        return s


class StoreDetail(DetailView):
    template_name = 'core/store_detail.html'
    model = Store


class SomeProtectedView(GroupRequiredMixin, TemplateView):
    template_name = 'core/logged.html'
    group_required = u'Diretor'


def adduser(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            return render(request, 'index.html')
    else:
        form = UserForm()
    return render(request, 'adduser.html', {'form': form})

bookstore/core/templates/core/book_list.html
{% extends "base.html" %}

{% block title %}
    <title>Book List</title>
{% endblock title %}

{% block content %}

    <form class="navbar-form navbar-right" action="." method="get">
        <!-- add -->
        <a href="#">
            <button id="new_register" type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span> Adicionar
            </button>
        </a>
        <!-- search form -->
        <div class="form-group">
            <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
            <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
        </div>
    </form>

    <h1>Lista de {{ name_plural.capitalize }}</h1>

<div>
{% if books %}
  <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
    <thead>
      <tr>
        <th class="mdl-data-table__cell--non-numeric">Nome</th>
        <th class="mdl-data-table__cell--non-numeric">Autor</th>
        <th class="mdl-data-table__cell--non-numeric">Editora</th>
      </tr>
    </thead>
    <tbody>
      {% for book in books %}
        <tr>
          <td class="mdl-data-table__cell--non-numeric">{{ book.name }}</td>
          <td class="mdl-data-table__cell--non-numeric">
            {% if book.authors.all.count == 1 %}
              {% for author in book.authors.all %}
                {{ author.name }}
              {% endfor %}
            {% else %}
                <a href="">vários autores</a>
            {% endif %}
          </td>
          <td class="mdl-data-table__cell--non-numeric">{{ book.publisher }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}
</div>

<hr>
<div>
    <h3><b>Total:</b> {{ count }}
        {% if count <= 1 %}
            {{ name }}
        {% else %}
            {{ name_plural }}
        {% endif %}
    </h3>
</div>

<!-- pagination -->
{% include "pagination.html" %}

{% endblock content %}

bookstore/core/templates/core/customer_list.html
{% extends "base.html" %}

{% block title %}
    <title>Customer List</title>
{% endblock title %}

{% block content %}

    <form class="navbar-form navbar-right" action="." method="get">
        <!-- add -->
        <a href="#">
            <button id="new_register" type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span> Adicionar
            </button>
        </a>
        <!-- search form -->
        <div class="form-group">
            <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
            <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
        </div>
    </form>

    <h1>Lista de {{ name_plural.capitalize }}</h1>

    <div>
        {% if customers %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Nascimento</th>
                        <th class="text-center">Ativo</th>
                    </tr>
                </thead>
                <tbody>
                {% for customer in customers %}
                    <tr>
                        <td>{{ customer.full_name }}, {{ customer.get_treatment_display }}</td>
                        <td>{{ customer.email }}</td>
                        <td>{{ customer.birthday|date:"d/m/Y" }}</td>
                        
                        <td class="text-center">
                            {% if customer.active %}
                                <span class="glyphicon glyphicon-ok-sign" style="color: #44AD41"></span>
                            {% else %}
                                <span class="glyphicon glyphicon-minus-sign" style="color: #DE2121"></span>
                            {% endif %}
                        </td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="alert alert-warning">Sem itens na lista.</p>
        {% endif %}
    </div>

    <hr>
    <div>
        <h3><b>Total:</b> {{ count }}
            {% if count <= 1 %}
                {{ name }}
            {% else %}
                {{ name_plural }}
            {% endif %}
        </h3>
    </div>


<!-- pagination -->
{% include "_pagination.html" %}

{% endblock content %}

bookstore/core/templates/core/denied.html
{% extends "base.html" %}

{% block title %}
    <title>Access denied</title>
{% endblock title %}

{% block content %}

	<h2>Acesso negado!</h2>
	<a href="{ url 'home' }">Home</a>

{% endblock content %}

bookstore/core/templates/core/logged.html
{% extends "base.html" %}

{% block title %}
    <title>Logged</title>
{% endblock title %}

{% block content %}

	<h2>Você está logado como {{ user.groups.first.name }}</h2>

{% endblock content %}

bookstore/core/templates/core/store_detail.html
{% extends "base.html" %}

{% block title %}
    <title>Store Detail</title>
{% endblock title %}

{% block content %}

	<ul class="breadcrumb">
		<li><a href="{% url 'store_list' %}">Lojas</a> <span class="divider"></span></li>
		<li class="active">{{ object.name }}</li>
	</ul>

	<div class="col-sm-6 col-md-4">
		<div class="list-group">
			<h1>Loja: {{ object.name }}</h1>
			
			{% for item in object.books.all %}
				<div class="list-group-item">
					<h4>{{ item.name }}</h4>
				</div>
			{% endfor %}
		</div>
	</div>

{% endblock content %}

bookstore/core/templates/core/store_list.html
{% extends "base.html" %}

{% block title %}
    <title>Store List</title>
{% endblock title %}

{% block content %}

    <form class="navbar-form navbar-right" action="." method="get">
        <!-- add -->
        <a href="#">
            <button id="new_register" type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span> Adicionar
            </button>
        </a>
        <!-- search form -->
        <div class="form-group">
            <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
            <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
        </div>
    </form>

    <h1>Lista de {{ name_plural.capitalize }}</h1>

    <div>
        {% if stores %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Loja</th>
                        <th>Livros</th>
                    </tr>
                </thead>
                <tbody>
                {% for store in stores %}
                    <tr>
                        <td>{{ store.name }}</td>
                        <td><a href="{{ store.get_absolute_url }}">{{ store.books.all.count }}</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="alert alert-warning">Sem itens na lista.</p>
        {% endif %}
    </div>

    <hr>
    <div>
        <h3><b>Total:</b> {{ count }}
            {% if count <= 1 %}
                {{ name }}
            {% else %}
                {{ name_plural }}
            {% endif %}
        </h3>
    </div>


<!-- pagination -->
{% include "pagination.html" %}

{% endblock content %}